[build]
  command = "npm run build" # or "yarn build"
  publish = "build" # directory where build output is located

[build.environment]
  NODE_VERSION = "14" # specify your Node.js version if needed
